name: elibmobile
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.3.1"

dependencies:
  flutter:
    sdk: flutter
    
  google_fonts: ^2.1.0 
  percent_indicator: ^3.0.1
  cupertino_icons: ^1.0.2
  easy_splash_screen:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/splash/
